---
id: ruby30th-lt
base_name: slide
tags: []
presentation_date:
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1200
height: 675
author:
  markup_language: :rd
  name:
  email:
  rubygems_user:
  slideshare_user:
  speaker_deck_user:
